### PR TITLE
Fix numeric constant detection for stand alone 0

### PR DESCRIPTION
**Pull request by AEgan**
Recently, after installing Atom 1.10 beta (currently using beta 6), I noticed syntax highlighting for stand alone `0`s was not properly detected in ruby. I noticed the regex detection changed between the version I was using for Atom 1.9 and the 1.10 beta. Instead of opening an issue I tried to propose a solution and take a crack at solving it myself.

before:
screen shot 2016-08-23 at 9 24 14 am

after:
screen shot 2016-08-23 at 9 23 44 am

This makes anything following a 0 for a hex constant, binary etc, optional so that a 0 on its own is detected as numeric constant.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can https://github.com/atom/language-ruby/pull/163/files#diff-e6c5c2e163c647d0b92203493f43f877R354 be changed to `[\\d](?>_?\\d)*` instead?

**Comment by AEgan** [comment]
@50Wliu made the change, thanks for the suggestion. regex isn't my forte!

**Comment by esdoppio** [comment]
👍  @50Wliu 

`0(?:…)?` doesn't really solve the problem, coz it still doesn't capture something like "0.99".

Fwiw, besides "0", `\d(?>_?\d)*` also matches "0999", which raises a SyntaxError (numeric literals beginning with 0 are expected to be an octal number). But people rarely do that, and it's not the language package's job to prevent errors, so I think it's ok.

Putting `\d` in a char class is unnecessary. 😉

**Comment by AEgan** [comment]
@50Wliu @esdoppio thanks for taking a look at this!

**Pull request merged**
