### PR TITLE
Suppress a coffeelint error no_interpolation_in_single_quotes

### PR DESCRIPTION
**Pull request by kachick**
ref: https://github.com/clutchski/coffeelint/issues/460

Just to suppress

### CODE REVIEW

**Comment by kachick** [comment]
Closed and re-opened because I got AppVeyor weird non building error... ref: https://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable

**Comment by 50Wliu** [comment]
Can you add a comment explaining why the single backslash was added?  Just for future reference.  Thanks!

**Comment by kachick** [comment]
Thank you! Is https://github.com/atom/language-ruby/pull/162/commits/c69251b6598691624c1804c9efad628460423570 enough?

**Comment by 50Wliu** [comment]
Yep, thanks!

**Comment by kachick** [comment]
☺️

**Pull request merged**
