### PR TITLE
Update language-ruby.cson

### PR DESCRIPTION
**Pull request by peterzhu2118**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Typing `>` (tags in HTML) in `.html.erb` files auto suggests `>-` and `>=`, which are ridiculously annoying since it gets replaced when the enter key is pressed. 

### Benefits

Prevents me (and possibly others) from getting mad.

### CODE REVIEW

**Comment by schacon** [comment]
👍 for the love of god. About a month ago this started happening and it makes writing erb a nightmare. I've tried overwriting these snippets in local cson and I can't get it to not do it. If I don't hit 'esc' after every _single_ tag close if I want a newline after it, it autocompletes with `<%= %>`, lol.

screen shot 2018-01-06 at 5 59 32 pm

**Comment by 50Wliu** [comment]
Hmm, this may have something to do with the recent autocomplete changes.  @peterzhu2118 @schacon has this been happening for a while now or did it just start recently around the time of the Atom 1.22.0 release in November?

**Comment by peterzhu2118** [comment]
@50Wliu Definitely did not happen in September (then I stopped coding Rails for a while). I only know that it began last month when I continued to do Rails.

**Comment by peterzhu2118** [comment]
@50Wliu Could it be related to this issue atom/atom#16507?

**Comment by schacon** [comment]
Yeah, super recently - only in the last month or two.

**Comment by ungb** [comment]
@schacon @peterzhu2118 I'm having trouble reproing the exact issue here.  I tried to follow along with the repro steps in the PR as well as https://github.com/atom/language-ruby/pull/226#issuecomment-355793108

I tried latest Atom, 1.23.3, 1.22.0, 1.20.0 and still no luck seeing this work.  

Can you guys still repro?  Can you provide more info on how you're able to repro?  What version of atom and what packages you have installed(`apm list`)?

Thanks so much! 🙏

**Comment by peterzhu2118** [comment]
@ungb 
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Also, it can only be reproduced in a `.html.erb` file.

**Comment by ungb** [comment]
I followed the steps outlined with a `.html.erb` file in https://github.com/atom/language-ruby/pull/226#issue-158808216 and unable to repro.

@peterzhu2118 any chance you can provide the packages you have installed by running `apm list`?  

Does this repro in safe mode? `atom --safe`

A few others tried it out and couldn't repro either.  


/cc @50Wliu @Ben3eeE

**Comment by ungb** [comment]
Also, there are two issues that are known with autocomplete-snippet that should cause this not to show up since these are considered non-word characters. 

see: 
https://github.com/atom/autocomplete-snippets/issues/67
https://github.com/atom/autocomplete-snippets/issues/56

**Comment by peterzhu2118** [comment]
@ungb This problem doesn't seem to happen anymore. I've tested both on my desktop and my laptop. Maybe it's because of Atom updates between then and now? I wonder if @schacon can confirm whether this is still happening. 

Here is `apm list` in case you still need it:
```
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.5
├── autocomplete-css@0.17.4
├── autocomplete-html@0.8.3
├── autocomplete-plus@2.40.0
├── autocomplete-snippets@1.11.2
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.88.0
├── command-palette@0.42.0
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.3
├── markdown-preview@0.159.18
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.3.1
├── package-generator@1.1.1
├── settings-view@0.253.1-0
├── snippets@1.1.9
├── spell-check@0.72.5
├── status-bar@1.8.14
├── styleguide@0.49.8
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.0
├── tree-view@0.221.3
├── update-package-dependencies@0.12.0
├── welcome@0.36.6 (disabled)
├── whitespace@0.37.5
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.7
├── language-gfm@0.90.2
├── language-git@0.19.1
├── language-go@0.44.3
├── language-html@0.48.5
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.6
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.42.2
├── language-property-list@0.9.1
├── language-python@0.45.5
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.2
├── language-xml@0.35.2
└── language-yaml@0.31.1

Community Packages (9) C:\Users\Peter\.atom\packages
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── intentions@1.1.5
├── language-latex@1.1.1
├── latex@0.49.0
├── linter@2.2.0
├── linter-ui-default@1.6.10
├── pdf-view@0.62.0
└── script@3.17.3
```

**Comment by schacon** [comment]
Hm. It still does it for me, even in safe mode. I'm on 1.23.2, which Atom says is the latest version.

screen recording 2018-01-23 at 05 39 pm

```
$ apm list
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.5
├── autocomplete-css@0.17.4
├── autocomplete-html@0.8.3
├── autocomplete-plus@2.38.0
├── autocomplete-snippets@1.11.2
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.88.0
├── command-palette@0.42.0
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.3
├── markdown-preview@0.159.18
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.3.1
├── package-generator@1.1.1
├── settings-view@0.253.0
├── snippets@1.1.9
├── spell-check@0.72.3 (disabled)
├── status-bar@1.8.14
├── styleguide@0.49.8
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.0
├── tree-view@0.221.3
├── update-package-dependencies@0.12.0
├── welcome@0.36.6
├── whitespace@0.37.5
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.7
├── language-gfm@0.90.2
├── language-git@0.19.1
├── language-go@0.44.3
├── language-html@0.48.5
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.6
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.42.2
├── language-property-list@0.9.1
├── language-python@0.45.5
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.2
├── language-xml@0.35.2
└── language-yaml@0.31.1

Dev Packages (1) /Users/schacon/.atom/dev/packages
└── language-ruby@0.71.4

Community Packages (20) /Users/schacon/.atom/packages
├── atom-ide-ui@0.7.2
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── execute-as-ruby@0.2.1 (disabled)
├── file-icons@2.1.15
├── git-time-machine@1.5.9
├── imdone-atom@2.3.29 (disabled)
├── imdone-atom-github@0.1.11 (disabled)
├── intentions@1.1.5
├── language-babel@2.81.1
├── language-javascript-jsx@0.3.7
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.0
├── linter-rubocop@2.2.0 (disabled)
├── linter-ruby@1.2.6 (disabled)
├── linter-ruby-lint@1.2.0 (disabled)
├── linter-ui-default@1.6.10 (disabled)
├── pigments@0.40.2
├── teletype@0.5.0 (disabled)
└── todo-show@2.1.0 (disabled)
```

If it's not a problem for anyone else and it was fixed for @ungb randomly, hopefully someday it will disappear for me too. 😄 

Don't worry about it, I've gotten used to slapping the `esc` key after every tag close now.

**Comment by 50Wliu** [comment]
@schacon that's interesting, the latest version is actually 1.23.3 which includes some autocomplete fixes regarding non-word characters.  Can you try to update manually?
https://github.com/atom/atom/releases/tag/v1.23.3

**Comment by schacon** [comment]
You're right @50Wliu, 1.23.3 fixed it for me. Thanks for all your attention and work here, I really appreciate it. You can close this. 🥇

**Pull request closed without merging**
