### PR TITLE
add support for Ruby 2.3's new "safe navigation operator"

### PR DESCRIPTION
**Pull request by rubysolo**
https://bugs.ruby-lang.org/issues/11537

### CODE REVIEW

**Comment by 50Wliu** [comment]
Should the `&` be tokenized separately?

**Comment by rubysolo** [comment]
That's a good question -- I'm not sure.  If I think about `&.` as being an "operator", then it seems like it should be a single token.  However, if I think about it as shorthand for `&& .`, then maybe it should be tokenized separately.

**Comment by envygeeks** [comment]
`&.` is an operator, it is thee operator: https://github.com/ruby/ruby/blob/837babd56459aafc1232a12fbfa783025d619b98/parse.y#L878

**Comment by envygeeks** [comment]
And yes I mean thee, because it's officially my favorite operator in Ruby.

**Comment by 50Wliu** [comment]
Awesome!

**Comment by mneumark** [comment]
At RubyConf, Matz referred to it as "The Lonely Operator". If you were wondering...

**Comment by envygeeks** [comment]
In every other language it's called a safe navigation operator, I think I'll keep referring to it as that.

**Comment by mneumark** [comment]
Thats fine. That is the practical name since it describes what it does. In other languages it usually uses `?.` rather than `&.` but because you can use a `?` in variables and methods in ruby, you can't use a `?` in an operator. Since it looks different, I guess it got that nickname from the language's creator. It was more of a random note that seemed relevant.

**Pull request merged**
